// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SchurPolRcpp
Rcpp::List SchurPolRcpp(int n, Rcpp::IntegerVector lambda);
RcppExport SEXP _jack_SchurPolRcpp(SEXP nSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(SchurPolRcpp(n, lambda));
    return rcpp_result_gen;
END_RCPP
}
// test
void test();
RcppExport SEXP _jack_test() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jack_SchurPolRcpp", (DL_FUNC) &_jack_SchurPolRcpp, 2},
    {"_jack_test", (DL_FUNC) &_jack_test, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_jack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
