# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SchurPolRcpp <- function(n, lambda) {
    .Call(`_jack_SchurPolRcpp`, n, lambda)
}

JackPolRcpp <- function(n, lambda, alpha) {
    .Call(`_jack_JackPolRcpp`, n, lambda, alpha)
}

JackEvalRcpp_gmpq <- function(x, lambda, alpha) {
    .Call(`_jack_JackEvalRcpp_gmpq`, x, lambda, alpha)
}

JackEvalRcpp_double <- function(x, lambda, alpha) {
    .Call(`_jack_JackEvalRcpp_double`, x, lambda, alpha)
}

SchurEvalRcpp_gmpq <- function(x, lambda) {
    .Call(`_jack_SchurEvalRcpp_gmpq`, x, lambda)
}

SchurEvalRcpp_double <- function(x, lambda) {
    .Call(`_jack_SchurEvalRcpp_double`, x, lambda)
}

test <- function() {
    invisible(.Call(`_jack_test`))
}

