# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SchurPolRcpp <- function(n, lambda) {
    .Call(`_jack_SchurPolRcpp`, n, lambda)
}

JackPolRcpp <- function(n, lambda, alpha) {
    .Call(`_jack_JackPolRcpp`, n, lambda, alpha)
}

JackEvalRcpp <- function(x, lambda, alpha) {
    .Call(`_jack_JackEvalRcpp`, x, lambda, alpha)
}

test <- function() {
    invisible(.Call(`_jack_test`))
}

